### ISSUE TITLE
Complication is not updating

### ISSUE THREAD

**Issue by inspirit** [jverkoey/ElectricSidecar#35] opened 2023-01-16 06:24 UTC
After successful login I can see all the info inside the watch app but the complication on screen is not updating 
tried to switch to door status the result is empty (lates watch os + Ultra model)
![WhatsApp Image 2023-01-16 at 07 14 18](https://user-images.githubusercontent.com/223020/212611633-1fb08699-9f76-4a0b-9a92-5fff76b2d405.jpeg)

**Comment by gcandau** [comment] 2023-01-16 06:34
Hi,
Same for me 😄 
Login is OK, all details related to the car are present in the app, but none of the complications are being updated

**Comment by jverkoey** [comment] 2023-01-16 06:44
I haven't quite figured out why the complications do this on first log in; may be some sort of synchronization issue. It tends to sort itself out within some period of time which has made it somewhat difficult to reproduce.

Let me know if it doesn't eventually start showing the right thing. You can also force a refresh in the app with the refresh button — that should cause the complication to refresh.

**Comment by gcandau** [comment] 2023-01-16 07:12
I already tried the refresh button in the app, but still nothing being showed.
Let's see if it works after some more hours, but perhaps something related to locales like for previous auth issue?

**Comment by jverkoey** [comment] 2023-01-16 07:20
Is the app itself working?

**Comment by jverkoey** [comment] 2023-01-16 07:22
Ah, nevermind, re-read your comments.

**Comment by gcandau** [comment] 2023-01-16 07:23
Yes, app is perfect. Only the complications are not being showed & refreshed when selected.

**Comment by gcandau** [comment] 2023-01-16 07:28
Wait wait wait, just now it has been updated and showed correctly.
Looks like you were right, only a question of time 🙂

**Comment by inspirit** [comment] 2023-01-16 07:59
It still struggling for me :( after some time http errors appear (see attachments) and no change from that state.
after reinstall and fresh login i still see the same http errors...
![WhatsApp Image 2023-01-16 at 08 51 29](https://user-images.githubusercontent.com/223020/212626207-a3af0020-3f02-4483-b462-40cb2f6476db.jpeg)
![WhatsApp Image 2023-01-16 at 08 51 30](https://user-images.githubusercontent.com/223020/212626223-2e0cc4a6-db9f-46e3-92d9-66519324daf1.jpeg)

**Comment by jverkoey** [comment] 2023-01-16 08:23
Hmm looks like auth failures for you @inspirit. When you delete the app and reinstall is it asking you to log in? I wonder if it's maybe gotten into some weird intermediate state with the locale changing.

**Comment by inspirit** [comment] 2023-01-16 08:24
yes it asked for login details

**Comment by gcandau** [comment] 2023-01-16 08:51
Hi again,
Same issue for me now. Also, I do not know if there's a link, but the official Porsche connect app is not able to connect to the car anymore. Looks like a ban (perhaps too many auth) or something like that...

**Comment by jverkoey** [comment] 2023-01-16 13:34
I'm still able to connect, so it might be a temporary issue with PorscheConnect. Might be worth waiting a day to see if it resolves itself. In the meanwhile I'll look into adding some kind of anonymized logging output that you can share manually so that we can try to debug what's happening.

**Comment by jverkoey** [comment] 2023-01-16 23:00
Looks like everyone was having an outage today. Can you try installing the v8 build and then reinstalling the v10 build? That fixed the weirdness for me.

**Comment by jverkoey** [comment] 2023-01-17 07:08
I've pushed v11 which introduces some thread-safety around how auth tokens are stored/retrieved. Hopefully this improves the stability of the app, though I can't quite be certain that that's the root cause of this issue.

**Comment by jverkoey** [comment] 2023-01-17 15:35
Try deleting the app from your watch and reinstalling; not an ideal fix but might kick the complication into gear.

**Comment by inspirit** [comment] 2023-01-17 15:36
that what i did in the morning with latest version you pushed to testflight :)

**Comment by jverkoey** [comment] 2023-01-17 15:38
Mysterious! I will take a stab at debugging why the complications aren't updating consistently in my next hack session then.

**Comment by jverkoey** [comment] 2023-01-19 06:29
Ah hah! I figured this out thanks to the new logging I added. Turns out that because the complications are built using WidgetKit, they're not actually complications and accordingly can't be refreshed using the complications APIs. Instead, I have to refresh the complications using WidgetKit like so: `WidgetCenter.shared.reloadAllTimelines()`. New build inbound!

**Comment by jverkoey** [comment] 2023-01-19 06:37
Should be fixed in 6be6fd378822bf2ff2a79863f039d0b1f157d67e.

**Closed by jverkoey** 2023-01-19 06:37 UTC
Labels: bug, context:complication
