### ISSUE TITLE
Infinite spinning animation trying to login

### ISSUE THREAD

**Issue by inspirit** [jverkoey/ElectricSidecar#30] opened 2023-01-15 18:32 UTC
Hi, I got an infinite spinning animation after input login/pass and pressing 'login'
seems like it cant connect for some reason but no error messages and not clear if it keeps retrying or just showing spinning wheel animation...

**Comment by jverkoey** [comment] 2023-01-15 18:36
It can sometimes take a minute or so to log in the first time, but it's also possible I introduced a regression. Will see if I can reproduce.

Is your watch paired with an iPhone? And is your phone on Wi-Fi?

**Comment by inspirit** [comment] 2023-01-15 18:38
yup, the watch is paired and i'm on my home wifi. been waiting for 10 minutes :) with no change in spinning animation. tried to reinstall still the same

**Comment by jverkoey** [comment] 2023-01-15 18:38
Hmm no luck reproducing with a clean install. Log in took ~5-10 seconds.

I do think I can improve the login flow to give a bit more clarity about the steps it's taking to log in (there's essentially two steps).

**Comment by jverkoey** [comment] 2023-01-15 18:40
Oh, what locale is your phone based in? I wonder if the locale determination is messing up the auth flow...

This is what my locale looks like (Settings > General > Language & Region):

![IMG_3617](https://user-images.githubusercontent.com/45670/212560454-8a33064d-546d-41aa-9d1a-34a7b77f98a9.PNG)

**Comment by inspirit** [comment] 2023-01-15 18:43
![Screenshot 2023-01-15 at 19 41 46](https://user-images.githubusercontent.com/223020/212560628-76840b0e-0145-4458-95d3-4423d6904b14.png)

**Comment by gcandau** [comment] 2023-01-15 21:42
Hi,
I've the same issue as well. I'm based in the EU (France). Could it be something related to localization ?

**Comment by jverkoey** [comment] 2023-01-16 04:54
Looking into this now.

**Comment by jverkoey** [comment] 2023-01-16 05:08
This is likely resolved by 9a9dd56c1e46cd91bff9e2e9818eb2e15e7cdb2e. Pushing a built out to TestFlight meow.

**Comment by jverkoey** [comment] 2023-01-16 05:49
Filed https://github.com/jverkoey/ElectricSidecar/issues/34 for a potential improvement to the auth flow.

**Closed** 2023-01-16 05:49 UTC
Labels: bug, context:watch app
